global: 
  scrape_interval: 1m

scrape_configs: 
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node" 
    static_configs: 
    - targets: ["node-exporter:9100"]

  - job_name: "cadvisor" 
    scrape_interval: 5s 
    static_configs: 
    - targets: ["172.19.0.6:8080"]  

  - job_name: pfsense
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["10.0.0.254:9100"]

  - job_name: ironman
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["10.0.0.25:9182"]      